# Site Info
title: Jistol Github Page
tagline: 'A Jekyll theme based on Lanyon'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
# url: http://codinfox.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: 김지환
  description: 열심히 공부하는 개발자.
  gravatar: 034519c72194a93612b79ac8dc273424 # md5 hash of your email address
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/jistol
    facebook:  https://www.facebook.com/jistol.kim
    #twitter:   https://twitter.com/Li_Zhihao
    #weibo:     http://weibo.com/41173780
    email:     http://www.google.com/recaptcha/mailhide/d?k=019csu4eVzJbvc1nXWueVk-w==&c=ZGJUNb6dJ6dwB9T34n_MZ0U5i2OntxTAksH_KpBdN2E=

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Post:
    - '/blog/'
  Categories:
    - '/blog/categories/'
  Tags:
    - '/blog/tags/'
  About:
    - '/about/'
  Github Project:
    - 'https://github.com/jistol'


# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-89877408-1' # leave blank if you don't want google analytics
naver_analytics_token: '1293c760f8c51'
disqus_short_name: 'jistol-github-io' # leave blank if you don't want disqus
